import Foundation

/// The shell scripts Vedetta writes into ~/.vedetta/bin, as pure
/// templates so the test suite can syntax-check them (`zsh -n` /
/// `bash -n`). Vibe Island 1.0.41 ships a launcher whose self-cleanup
/// branch dies on a parse error and never runs — this is the guard
/// against shipping the same fate.
public enum RuntimeScripts {
    /// The hook launcher: resolves the real helper inside the app bundle
    /// (fixed paths → cache → mdfind) and, when the app has been gone for
    /// over 5 minutes, cleans every trace of Vedetta out of the configs.
    public static func launcher(bundlePath: String) -> String {
        """
        #!/bin/zsh
        # vedetta-bridge launcher (auto-generated by Vedetta, do not edit)
        H=/Contents/Helpers/vedetta-bridge
        O="$HOME/.vedetta/.orphaned"
        C="$HOME/.vedetta/bin/.bridge-cache"
        for P in "\(bundlePath)" "/Applications/Meowtch.app" "$HOME/Applications/Meowtch.app" "/Applications/Vedetta.app" "$HOME/Applications/Vedetta.app"; do
          B="${P}${H}"
          if [ -x "$B" ]; then /bin/rm -f "$O"; exec "$B" "$@"; fi
        done
        if [ -f "$C" ]; then
          read -r P < "$C"; B="${P}${H}"
          if [ -x "$B" ]; then /bin/rm -f "$O"; exec "$B" "$@"; fi
        fi
        P="$(/usr/bin/mdfind "kMDItemCFBundleIdentifier == 'app.vedetta.macos'" 2>/dev/null | /usr/bin/head -1)"
        B="${P}${H}"
        if [ -n "$P" ] && [ -x "$B" ]; then echo "$P" > "$C"; /bin/rm -f "$O"; exec "$B" "$@"; fi
        # ── app not found: self-cleanup after a 5-minute grace period ──
        if [ -f "$O" ]; then
          read -r T < "$O"
          if [ "$(( $(/bin/date +%s) - T ))" -ge 300 ]; then
            S="$(/bin/date -u +%Y-%m-%dT%H-%M-%SZ).$$"
            [ -f "$HOME/.claude/settings.json" ] && /bin/cp -p "$HOME/.claude/settings.json" "$HOME/.vedetta/backups/settings.json.$S"
            [ -f "$HOME/.codex/hooks.json" ] && /bin/cp -p "$HOME/.codex/hooks.json" "$HOME/.vedetta/backups/hooks.json.$S"
            /usr/bin/osascript -l JavaScript <<'JSEOF' 2>/dev/null
        ObjC.import('Foundation')
        var h=ObjC.unwrap($.NSHomeDirectory()),m='vedetta'
        function rd(p){var d=$.NSData.alloc.initWithContentsOfFile(p);if(!d||!d.length)return null;return ObjC.unwrap($.NSString.alloc.initWithDataEncoding(d,$.NSUTF8StringEncoding))}
        function wr(p,s){$.NSString.alloc.initWithUTF8String(s).writeToFileAtomicallyEncodingError(p,true,$.NSUTF8StringEncoding,null)}
        function clean(p){var s=rd(p);if(!s)return;var j;try{j=JSON.parse(s)}catch(e){return}var ch=false;if(j.hooks){for(var ev in j.hooks){var a=j.hooks[ev];if(!Array.isArray(a))continue;var f=a.filter(function(e){if(Array.isArray(e.hooks)){e.hooks=e.hooks.filter(function(x){return(x.command||'').indexOf(m)===-1});if(!e.hooks.length)return false}return(e.command||'').indexOf(m)===-1});if(f.length!==a.length)ch=true;if(!f.length)delete j.hooks[ev];else j.hooks[ev]=f}if(!Object.keys(j.hooks).length)delete j.hooks}if(j.statusLine&&(j.statusLine.command||'').indexOf(m)!==-1){delete j.statusLine;ch=true}if(ch)wr(p,JSON.stringify(j,null,2))}
        clean(h+'/.claude/settings.json')
        clean(h+'/.codex/hooks.json')
        JSEOF
            for cli in code code-insiders cursor windsurf; do
              command -v "$cli" >/dev/null 2>&1 && "$cli" --uninstall-extension vedetta.terminal-focus >/dev/null 2>&1 &
            done
            /bin/rm -f "$HOME/.vedetta/bin/vedetta-bridge" "$HOME/.vedetta/bin/vedetta-statusline" "$C" "$O"
          fi
        else
          /bin/date +%s > "$O"
        fi
        exit 0
        """
    }

    /// The statusline harvester: captures `rate_limits` from the
    /// statusline JSON into the account's cache file, printing nothing.
    public static func statusLine(cacheFile: String) -> String {
        """
        #!/bin/bash
        # Vedetta statusline (auto-generated): captures rate_limits for the
        # usage strip. Add your own status output below — this file is only
        # rewritten if you delete it.
        input=$(cat)
        _rl=$(printf '%s' "$input" | /usr/bin/jq -c '.rate_limits // empty' 2>/dev/null)
        [ -n "$_rl" ] && printf '%s\\n' "$_rl" > "\(cacheFile)"
        """
    }
}
