import Foundation
import VedettaKit

/// Filesystem-facing setup: runtime directories, the launcher script in
/// `~/.vedetta/bin`, and hook install/removal in `~/.claude/settings.json`
/// (always with a timestamped backup first).
enum VedettaSetup {
    static let home = NSHomeDirectory()
    static var rootDir: String { home + "/.vedetta" }
    static var binDir: String { rootDir + "/bin" }
    static var runDir: String { rootDir + "/run" }
    static var backupsDir: String { rootDir + "/backups" }
    static var socketPath: String { runDir + "/vedetta.sock" }
    static var launcherPath: String { binDir + "/vedetta-bridge" }
    static var claudeSettingsPath: String { home + "/.claude/settings.json" }

    // MARK: - Runtime layout

    static func ensureRuntimeLayout() throws {
        let fm = FileManager.default
        for dir in [binDir, runDir, backupsDir] {
            try fm.createDirectory(atPath: dir, withIntermediateDirectories: true)
        }
        try writeLauncher()
    }

    /// The launcher resolves the real helper inside the app bundle, so the
    /// hooks survive app updates and disappear gracefully with the app.
    private static func writeLauncher() throws {
        let bundlePath = Bundle.main.bundlePath
        let script = """
        #!/bin/zsh
        # vedetta-bridge launcher (auto-generated by Vedetta, do not edit)
        H=/Contents/Helpers/vedetta-bridge
        for P in "\(bundlePath)" "/Applications/Vedetta.app" "$HOME/Applications/Vedetta.app"; do
          B="${P}${H}"; [ -x "$B" ] && exec "$B" "$@"
        done
        exit 0
        """
        try script.write(toFile: launcherPath, atomically: true, encoding: .utf8)
        chmod(launcherPath, 0o755)
    }

    // MARK: - Claude Code hooks

    static func claudeHooksInstalled() -> Bool {
        guard let settings = readClaudeSettings() else { return false }
        return HookConfigurator.isInstalled(in: settings)
    }

    @discardableResult
    static func installClaudeHooks() throws -> Bool {
        let settings = readClaudeSettings() ?? [:]
        let (merged, changed) = HookConfigurator.mergingHooks(into: settings)
        guard changed else { return false }
        try backupClaudeSettings()
        try writeClaudeSettings(merged)
        return true
    }

    @discardableResult
    static func removeClaudeHooks() throws -> Bool {
        guard let settings = readClaudeSettings() else { return false }
        let (stripped, changed) = HookConfigurator.removingHooks(from: settings)
        guard changed else { return false }
        try backupClaudeSettings()
        try writeClaudeSettings(stripped)
        return true
    }

    // MARK: - settings.json I/O

    private static func readClaudeSettings() -> [String: Any]? {
        guard let data = FileManager.default.contents(atPath: claudeSettingsPath) else { return nil }
        return (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
    }

    private static func backupClaudeSettings() throws {
        guard FileManager.default.fileExists(atPath: claudeSettingsPath) else { return }
        let stamp = ISO8601DateFormatter().string(from: Date())
            .replacingOccurrences(of: ":", with: "-")
        let destination = backupsDir + "/settings.json." + stamp
        try FileManager.default.copyItem(
            atPath: claudeSettingsPath,
            toPath: destination
        )
    }

    private static func writeClaudeSettings(_ settings: [String: Any]) throws {
        let data = try JSONSerialization.data(
            withJSONObject: settings,
            options: [.prettyPrinted, .sortedKeys]
        )
        try data.write(to: URL(fileURLWithPath: claudeSettingsPath), options: .atomic)
    }
}
