import Foundation
import VedettaKit

/// Filesystem-facing setup: runtime directories, the launcher script in
/// `~/.vedetta/bin`, and hook install/removal in `~/.claude/settings.json`
/// (always with a timestamped backup first).
enum VedettaSetup {
    static let home = NSHomeDirectory()
    static var rootDir: String { home + "/.vedetta" }
    static var binDir: String { rootDir + "/bin" }
    static var runDir: String { rootDir + "/run" }
    static var backupsDir: String { rootDir + "/backups" }
    static var socketPath: String { runDir + "/vedetta.sock" }
    static var launcherPath: String { binDir + "/vedetta-bridge" }
    static var claudeSettingsPath: String { home + "/.claude/settings.json" }

    // MARK: - Runtime layout

    static var cacheDir: String { rootDir + "/cache" }
    static var statusLinePath: String { binDir + "/vedetta-statusline" }

    static func ensureRuntimeLayout() throws {
        let fm = FileManager.default
        for dir in [binDir, runDir, backupsDir, cacheDir, rootDir + "/custom-sounds"] {
            try fm.createDirectory(atPath: dir, withIntermediateDirectories: true)
        }
        try writeLauncher()
        try writeStatusLineScript()
    }

    /// Harvests `rate_limits` from the statusline JSON into the cache;
    /// prints nothing (empty statusline) and leaves room for user code.
    private static func writeStatusLineScript() throws {
        let script = """
        #!/bin/bash
        # Vedetta statusline (auto-generated): captures rate_limits for the
        # usage strip. Add your own status output below — this file is only
        # rewritten if you delete it.
        input=$(cat)
        _rl=$(printf '%s' "$input" | /usr/bin/jq -c '.rate_limits // empty' 2>/dev/null)
        [ -n "$_rl" ] && printf '%s\\n' "$_rl" > "$HOME/.vedetta/cache/rl.json"
        """
        guard !FileManager.default.fileExists(atPath: statusLinePath) else { return }
        try script.write(toFile: statusLinePath, atomically: true, encoding: .utf8)
        chmod(statusLinePath, 0o755)
    }

    /// The launcher resolves the real helper inside the app bundle, so the
    /// hooks survive app updates and disappear gracefully with the app.
    private static func writeLauncher() throws {
        let bundlePath = Bundle.main.bundlePath
        let script = """
        #!/bin/zsh
        # vedetta-bridge launcher (auto-generated by Vedetta, do not edit)
        H=/Contents/Helpers/vedetta-bridge
        for P in "\(bundlePath)" "/Applications/Vedetta.app" "$HOME/Applications/Vedetta.app"; do
          B="${P}${H}"; [ -x "$B" ] && exec "$B" "$@"
        done
        exit 0
        """
        try script.write(toFile: launcherPath, atomically: true, encoding: .utf8)
        chmod(launcherPath, 0o755)
    }

    // MARK: - Claude Code hooks

    static func claudeHooksInstalled() -> Bool {
        guard let settings = readClaudeSettings() else { return false }
        return HookConfigurator.isInstalled(in: settings)
    }

    /// Self-heal on every launch: if we were installed but some events
    /// drifted (e.g. new hook events shipped in an update, or another app
    /// rewrote settings.json), re-merge the missing ones. Never installs
    /// from scratch — a settings.json with no vedetta hook is left as is,
    /// so a deliberate uninstall isn't undone.
    @discardableResult
    static func healClaudeHooks() throws -> Bool {
        guard let settings = readClaudeSettings(),
              HookConfigurator.hasAnyHook(in: settings),
              !HookConfigurator.isInstalled(in: settings) else { return false }
        return try installClaudeHooks()
    }

    @discardableResult
    static func installClaudeHooks() throws -> Bool {
        let settings = readClaudeSettings() ?? [:]
        let (merged, hooksChanged) = HookConfigurator.mergingHooks(into: settings)
        let (final, statusChanged) = HookConfigurator.installingStatusLine(
            into: merged,
            command: statusLinePath
        )
        guard hooksChanged || statusChanged else { return false }
        try backupClaudeSettings()
        try writeClaudeSettings(final)
        return true
    }

    @discardableResult
    static func removeClaudeHooks() throws -> Bool {
        guard let settings = readClaudeSettings() else { return false }
        let (stripped, changed) = HookConfigurator.removingHooks(from: settings)
        guard changed else { return false }
        try backupClaudeSettings()
        try writeClaudeSettings(stripped)
        return true
    }

    // MARK: - settings.json I/O

    private static func readClaudeSettings() -> [String: Any]? {
        guard let data = FileManager.default.contents(atPath: claudeSettingsPath) else { return nil }
        return (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
    }

    private static func backupClaudeSettings() throws {
        guard FileManager.default.fileExists(atPath: claudeSettingsPath) else { return }
        let stamp = ISO8601DateFormatter().string(from: Date())
            .replacingOccurrences(of: ":", with: "-")
        let destination = backupsDir + "/settings.json." + stamp
        try FileManager.default.copyItem(
            atPath: claudeSettingsPath,
            toPath: destination
        )
    }

    private static func writeClaudeSettings(_ settings: [String: Any]) throws {
        let data = try JSONSerialization.data(
            withJSONObject: settings,
            options: [.prettyPrinted, .sortedKeys]
        )
        try data.write(to: URL(fileURLWithPath: claudeSettingsPath), options: .atomic)
    }
}
