import Foundation
import VedettaKit

/// Filesystem-facing setup: runtime directories, the launcher script in
/// `~/.vedetta/bin`, and hook install/removal for Claude Code and Codex
/// (always with a timestamped backup before an existing file changes).
enum VedettaSetup {
    private static let configStore = HookConfigFileStore()
    private static let claudeRemovalKey = "hooks.deliberatelyRemoved.claude"
    private static let codexRemovalKey = "hooks.deliberatelyRemoved.codex"
    static let home = NSHomeDirectory()
    static var rootDir: String { home + "/.vedetta" }
    static var binDir: String { rootDir + "/bin" }
    static var runDir: String { rootDir + "/run" }
    static var backupsDir: String { rootDir + "/backups" }
    static var socketPath: String { runDir + "/vedetta.sock" }
    static var launcherPath: String { binDir + "/vedetta-bridge" }
    static var orphanedPath: String { rootDir + "/.orphaned" }
    static var claudeSettingsPath: String { home + "/.claude/settings.json" }
    static var codexHooksPath: String { home + "/.codex/hooks.json" }

    // MARK: - Runtime layout

    static var cacheDir: String { rootDir + "/cache" }
    static var statusLinePath: String { binDir + "/vedetta-statusline" }

    static func ensureRuntimeLayout() throws {
        let fm = FileManager.default
        for dir in [binDir, runDir, backupsDir, cacheDir, rootDir + "/custom-sounds"] {
            try fm.createDirectory(atPath: dir, withIntermediateDirectories: true)
        }
        // The app is alive: reset the launcher's orphan clock so a past
        // absence never counts toward the self-cleanup grace period.
        try? fm.removeItem(atPath: orphanedPath)
        try writeLauncher()
        try writeStatusLineScript()
    }

    /// Harvests `rate_limits` from the statusline JSON into the cache;
    /// prints nothing (empty statusline) and leaves room for user code.
    private static func writeStatusLineScript() throws {
        let script = """
        #!/bin/bash
        # Vedetta statusline (auto-generated): captures rate_limits for the
        # usage strip. Add your own status output below — this file is only
        # rewritten if you delete it.
        input=$(cat)
        _rl=$(printf '%s' "$input" | /usr/bin/jq -c '.rate_limits // empty' 2>/dev/null)
        [ -n "$_rl" ] && printf '%s\\n' "$_rl" > "$HOME/.vedetta/cache/rl.json"
        """
        guard !FileManager.default.fileExists(atPath: statusLinePath) else { return }
        try script.write(toFile: statusLinePath, atomically: true, encoding: .utf8)
        chmod(statusLinePath, 0o755)
    }

    /// The launcher resolves the real helper inside the app bundle, so the
    /// hooks survive app updates and disappear gracefully with the app. If the
    /// app has been gone for over 5 minutes (mdfind can't find it either), the
    /// launcher cleans up after itself — hooks, statusLine and the companion
    /// extension — so an uninstalled Vedetta leaves no trace, like the original.
    private static func writeLauncher() throws {
        let bundlePath = Bundle.main.bundlePath
        let script = """
        #!/bin/zsh
        # vedetta-bridge launcher (auto-generated by Vedetta, do not edit)
        H=/Contents/Helpers/vedetta-bridge
        O="$HOME/.vedetta/.orphaned"
        C="$HOME/.vedetta/bin/.bridge-cache"
        for P in "\(bundlePath)" "/Applications/Vedetta.app" "$HOME/Applications/Vedetta.app"; do
          B="${P}${H}"
          if [ -x "$B" ]; then /bin/rm -f "$O"; exec "$B" "$@"; fi
        done
        if [ -f "$C" ]; then
          read -r P < "$C"; B="${P}${H}"
          if [ -x "$B" ]; then /bin/rm -f "$O"; exec "$B" "$@"; fi
        fi
        P="$(/usr/bin/mdfind "kMDItemCFBundleIdentifier == 'app.vedetta.macos'" 2>/dev/null | /usr/bin/head -1)"
        B="${P}${H}"
        if [ -n "$P" ] && [ -x "$B" ]; then echo "$P" > "$C"; /bin/rm -f "$O"; exec "$B" "$@"; fi
        # ── app not found: self-cleanup after a 5-minute grace period ──
        if [ -f "$O" ]; then
          read -r T < "$O"
          if [ "$(( $(/bin/date +%s) - T ))" -ge 300 ]; then
            S="$(/bin/date -u +%Y-%m-%dT%H-%M-%SZ).$$"
            [ -f "$HOME/.claude/settings.json" ] && /bin/cp -p "$HOME/.claude/settings.json" "$HOME/.vedetta/backups/settings.json.$S"
            [ -f "$HOME/.codex/hooks.json" ] && /bin/cp -p "$HOME/.codex/hooks.json" "$HOME/.vedetta/backups/hooks.json.$S"
            /usr/bin/osascript -l JavaScript <<'JSEOF' 2>/dev/null
        ObjC.import('Foundation')
        var h=ObjC.unwrap($.NSHomeDirectory()),m='vedetta'
        function rd(p){var d=$.NSData.alloc.initWithContentsOfFile(p);if(!d||!d.length)return null;return ObjC.unwrap($.NSString.alloc.initWithDataEncoding(d,$.NSUTF8StringEncoding))}
        function wr(p,s){$.NSString.alloc.initWithUTF8String(s).writeToFileAtomicallyEncodingError(p,true,$.NSUTF8StringEncoding,null)}
        function clean(p){var s=rd(p);if(!s)return;var j;try{j=JSON.parse(s)}catch(e){return}var ch=false;if(j.hooks){for(var ev in j.hooks){var a=j.hooks[ev];if(!Array.isArray(a))continue;var f=a.filter(function(e){if(Array.isArray(e.hooks)){e.hooks=e.hooks.filter(function(x){return(x.command||'').indexOf(m)===-1});if(!e.hooks.length)return false}return(e.command||'').indexOf(m)===-1});if(f.length!==a.length)ch=true;if(!f.length)delete j.hooks[ev];else j.hooks[ev]=f}if(!Object.keys(j.hooks).length)delete j.hooks}if(j.statusLine&&(j.statusLine.command||'').indexOf(m)!==-1){delete j.statusLine;ch=true}if(ch)wr(p,JSON.stringify(j,null,2))}
        clean(h+'/.claude/settings.json')
        clean(h+'/.codex/hooks.json')
        JSEOF
            for cli in code code-insiders cursor windsurf; do
              command -v "$cli" >/dev/null 2>&1 && "$cli" --uninstall-extension vedetta.terminal-focus >/dev/null 2>&1 &
            done
            /bin/rm -f "$HOME/.vedetta/bin/vedetta-bridge" "$HOME/.vedetta/bin/vedetta-statusline" "$C" "$O"
          fi
        else
          /bin/date +%s > "$O"
        fi
        exit 0
        """
        try script.write(toFile: launcherPath, atomically: true, encoding: .utf8)
        chmod(launcherPath, 0o755)
    }

    // MARK: - Coding-agent hooks

    static func claudeHooksInstalled() -> Bool {
        guard let settings = try? configStore.read(at: URL(fileURLWithPath: claudeSettingsPath)) else { return false }
        return HookConfigurator.isInstalled(in: settings)
    }

    static func codexHooksInstalled() -> Bool {
        guard let settings = try? configStore.read(at: URL(fileURLWithPath: codexHooksPath)) else { return false }
        return HookConfigurator.codexHooksInstalled(in: settings)
    }

    /// Self-heal on every launch: if we were installed but some events
    /// drifted (e.g. new hook events shipped in an update, or another app
    /// rewrote settings.json), re-merge the missing ones. Never installs
    /// from scratch — a settings.json with no vedetta hook is left as is,
    /// so a deliberate uninstall isn't undone.
    @discardableResult
    static func healClaudeHooks() throws -> Bool {
        guard !UserDefaults.standard.bool(forKey: claudeRemovalKey),
              let settings = try? configStore.read(at: URL(fileURLWithPath: claudeSettingsPath)),
              HookConfigurator.hasAnyHook(in: settings),
              !HookConfigurator.isInstalled(in: settings) else { return false }
        return try installClaudeHooks()
    }

    @discardableResult
    static func healCodexHooks() throws -> Bool {
        guard !UserDefaults.standard.bool(forKey: codexRemovalKey),
              let settings = try? configStore.read(at: URL(fileURLWithPath: codexHooksPath)),
              HookConfigurator.hasAnyCodexHook(in: settings),
              !HookConfigurator.codexHooksInstalled(in: settings) else { return false }
        return try installCodexHooks()
    }

    @discardableResult
    static func installClaudeHooks() throws -> Bool {
        let result = try configStore.mutate(
            at: URL(fileURLWithPath: claudeSettingsPath),
            backupDirectory: URL(fileURLWithPath: backupsDir),
            backupName: "settings.json"
        ) { settings in
            let (merged, hooksChanged) = HookConfigurator.mergingHooks(into: settings)
            let (final, statusChanged) = HookConfigurator.installingStatusLine(
                into: merged,
                command: statusLinePath,
                canReplace: statusLineIsOrphan
            )
            return (final, hooksChanged || statusChanged)
        }
        UserDefaults.standard.set(false, forKey: claudeRemovalKey)
        return result.changed
    }

    @discardableResult
    static func installCodexHooks() throws -> Bool {
        let result = try configStore.mutate(
            at: URL(fileURLWithPath: codexHooksPath),
            backupDirectory: URL(fileURLWithPath: backupsDir),
            backupName: "hooks.json",
            transform: HookConfigurator.mergingCodexHooks
        )
        // Deliberately do not mutate ~/.codex/config.toml or synthesize
        // trusted_hash values. Codex owns that trust decision and asks the
        // user to review new hook commands on the next interactive launch.
        UserDefaults.standard.set(false, forKey: codexRemovalKey)
        return result.changed
    }

    @discardableResult
    static func installAgentHooks() -> HookAgentOperationReport {
        HookAgentOperationReport.run(
            claude: installClaudeHooks,
            codex: installCodexHooks
        )
    }

    @discardableResult
    static func removeClaudeHooks() throws -> Bool {
        defer { UserDefaults.standard.set(true, forKey: claudeRemovalKey) }
        guard FileManager.default.fileExists(atPath: claudeSettingsPath) else { return false }
        return try configStore.mutate(
            at: URL(fileURLWithPath: claudeSettingsPath),
            backupDirectory: URL(fileURLWithPath: backupsDir),
            backupName: "settings.json",
            transform: HookConfigurator.removingHooks
        ).changed
    }

    @discardableResult
    static func removeCodexHooks() throws -> Bool {
        defer { UserDefaults.standard.set(true, forKey: codexRemovalKey) }
        guard FileManager.default.fileExists(atPath: codexHooksPath) else { return false }
        return try configStore.mutate(
            at: URL(fileURLWithPath: codexHooksPath),
            backupDirectory: URL(fileURLWithPath: backupsDir),
            backupName: "hooks.json",
            transform: HookConfigurator.removingCodexHooks
        ).changed
    }

    @discardableResult
    static func removeAgentHooks() -> HookAgentOperationReport {
        HookAgentOperationReport.run(
            claude: removeClaudeHooks,
            codex: removeCodexHooks
        )
    }

    /// A foreign statusLine is claimable only when it is an orphan: every
    /// filesystem path it names is gone (e.g. another notch app that owned
    /// the slot was uninstalled). A live command — anything still pointing
    /// at an existing file — is left untouched.
    private static func statusLineIsOrphan(_ command: String) -> Bool {
        let fm = FileManager.default
        let paths = command
            .split(whereSeparator: { $0 == " " || $0 == "'" || $0 == "\"" })
            .map { $0.hasPrefix("~") ? home + $0.dropFirst() : String($0) }
            .filter { $0.hasPrefix("/") }
        // No path at all is unusual; don't claim in that ambiguous case.
        guard !paths.isEmpty else { return false }
        return !paths.contains { fm.fileExists(atPath: $0) }
    }

}
